language: python

cache: pip

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -r requirements_dev.txt
  - pip install -e .

# command to run tests
script:
  - pytest
  - sphinx-build -WT -b dummy docs/ docs/_build/html

# after_success:
#   - coveralls