language: python

cache: pip

python:
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -r docs/requirements.txt
  - pip install -e .

# command to run tests
script:
  - coverage run --source=src/ErnosCube -m pytest --runslow
  - python -m sphinx -WT -b dummy docs/ docs/_build/html

after_success:
  - coveralls
